//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordertable
    {
        public int Id { get; set; }
        public int Productid { get; set; }
        public int Quantity { get; set; }
        public double Totalprice { get; set; }
        public int Paymentid { get; set; }
        public int Userid { get; set; }
        public System.DateTime Created { get; set; }
    }
}
