//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userpayment
    {
        public int Id { get; set; }
        public int Userid { get; set; }
        public int Paymenttype { get; set; }
        public string Providername { get; set; }
        public int Accountno { get; set; }
    }
}
