//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdetail
    {
        public Userdetail()
        {
            this.Useraddresses = new HashSet<Useraddress>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public long Mobileno { get; set; }
        public int Created { get; set; }
        public string Email { get; set; }
        public int Usertype { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Useraddress> Useraddresses { get; set; }
    }
}
